package keep.core.model

sealed interface Chain {
    object Binance : Chain
    object Bitcoin : Chain
    object Ethereum : Chain
    object BinanceSmartChain : Chain
//    object AETERNITY : Chain
//    object AION,
//    object BITCOINCASH,
//    object BITCOINGOLD,
//    object CALLISTO,
//    object CARDANO,
//    ATOM,
//    DASH,
//    DECRED,
//    DIGIBYTE,
//    DOGECOIN,
//    EOS,
//    ETHEREUMCLASSIC,
//    FIO,
//    GOCHAIN,
//    GROESTLCOIN,
//    ICON,
//    IOTEX,
//    KAVA,
//    KIN,
//    LITECOIN,
//    MONACOIN,
//    NEBULAS,
//    NULS,
//    NANO,
//    NEAR,
//    NIMIQ,
//    ONTOLOGY,
//    POANETWORK,
//    QTUM,
//    XRP,
//    SOLANA,
//    STELLAR,
//    TEZOS,
//    THETA,
//    THUNDERTOKEN,
//    NEO,
//    TOMOCHAIN,
//    TRON,
//    VECHAIN,
//    VIACOIN,
//    WANCHAIN,
//    ZCASH,
//    FIRO,
//    ZILLIQA,
//    ZELCASH,
//    RAVENCOIN,
//    WAVES,
//    TERRA,
//    HARMONY,
//    ALGORAND,
//    KUSAMA,
//    POLKADOT,
//    FILECOIN,
//    ELROND,
//    BANDCHAIN,
//    SMARTCHAINLEGACY,
//    SMARTCHAIN,
//    OASIS,
//    POLYGON,
//    THORCHAIN,
//    BLUZELLE,
//    OPTIMISM,
//    ARBITRUM,
//    ECOCHAIN,
//    AVALANCHECCHAIN,
//    XDAI,
//    FANTOM,
//    CRYPTOORG,
//    CELO,
//    RONIN,
//    OSMOSIS,
//    ECASH
}