name: Release Framework

on:
  release:
    types: [ published ]

jobs:
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS Framework
        run: make ios-framework-release

      - name: Checksum
        run: make checksum

      - name: Add an asset to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            core-model/build/XCFrameworks/release/CoreModel.xcframework.zip
            core-blockchain/build/XCFrameworks/release/CoreBlockchain.xcframework.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}